Repository pulumi/docs, pull requests merged in 2019-06, with the labels that each got.

#1112 Add docs to show how to add support for detecting a new CI system in the CLI
  content/reference/cd-supporting-new-ci.md
  static/images/reference/supporting-new-ci/stack-update.png
Labels: impact/no-changelog-required

#1120 Add proper 301 redirects for our Node.js API docs
  infrastructure/index.ts
Labels: impact/no-changelog-required

#1122 Fix strange markdown rendering in API docs
  layouts/shortcodes/md.html
Labels: impact/no-changelog-required

#1138 style(quickstart): move diagrams below the fold & fix fonts + size used
  content/quickstart/_index.md
  content/quickstart/kubernetes/_index.md
  static/images/quickstart/general-architecture.svg
  static/images/quickstart/hourglass.svg
  static/images/quickstart/kubernetes/cake.svg
Labels: area/docs

#1135 Add sections to clarify dealing with inputs and outputs of a dynamic provider.
  content/reference/programming-model.md
Labels: impact/no-changelog-required

#1155 Update Python component examples
  content/reference/programming-model.md
Labels: area/docs, area/languages

#1163 Fix issue preventing use of fixed width font in code snippets
  assets/sass/partials/_forms.scss
  assets/sass/partials/_typography.scss
Labels: impact/no-changelog-required

#1161 Fix bug in langchoose and concat/minify/fingerprint scripts to cache bust
  assets/js/langchoose.js
  assets/js/main.js
  assets/js/noselect.js
  assets/js/search.js
  layouts/_default/search.html
  layouts/partials/scripts.html
Labels: impact/no-changelog-required

#1211 Generating the docs for the Datadog provider
  config.toml
  content/reference/pkg/nodejs/pulumi/datadog/_index.md
  content/reference/pkg/nodejs/pulumi/datadog/aws/_index.md
  content/reference/pkg/nodejs/pulumi/datadog/config/_index.md
  content/reference/pkg/nodejs/pulumi/datadog/gcp/_index.md
  content/reference/pkg/nodejs/pulumi/datadog/pagerduty/_index.md
  scripts/generate_python_docs.sh
  scripts/run_typedoc.sh
  scripts/update_repos.sh
  tools/pydocgen/pulumi-docs.json
  tools/tscdocgen/main.go
Labels: area/providers
