Repository pulumi/docs, pull requests merged in 2020-10, with the labels that each got.

#4318 Create Webinars Pages “securing-your-infrastructure-before-during-and-after-deployment/index-md”
  content/webinars/securing-your-infrastructure-before-during-and-after-deployment/index-md.md
  static/images/webinar/snyk-circleci-pulumi.png
Labels: netlify-cms/pending_publish

#4359 Update Webinars Pages “azure-infrastructure-as-code-workshop-2020-10-19/index”
  content/webinars/azure-infrastructure-as-code-workshop-2020-10-19/index.md
Labels: netlify-cms/pending_publish

#4334 Create Webinars Pages “workshop-gitops-with-pulumi-and-gitlab/index-md”
  content/webinars/workshop-gitops-with-pulumi-and-gitlab/index.md
  static/images/webinar/gitlab-demo.png
Labels: netlify-cms/pending_review

#4374 Update Webinars Pages “workshop-gitops-with-pulumi-and-gitlab/index”
  content/webinars/workshop-gitops-with-pulumi-and-gitlab/index.md
Labels: netlify-cms/pending_publish

#4386 Update Webinars Pages “azure-infrastructure-as-code-workshop-2020-10-19/index”
  content/webinars/azure-infrastructure-as-code-workshop-2020-10-19/index.md
Labels: netlify-cms/pending_publish

#4392 Update Events Pages “hacktoberfest-2020/index”
  content/events/hacktoberfest-2020/index.md
Labels: netlify-cms/draft

#4477 adding susan evans to team page
  data/team/team/susan-evans.toml
  static/images/team/susan-evans.jpg
Labels: area/docs
