Repository pulumi/docs, pull requests merged in 2021-03, with the labels that each got.

#5407 Update _index.md
  content/docs/guides/continuous-delivery/_index.md
Labels: automation/merge

#5501 Fix some broken links
  content/blog/intro-to-step-functions/index.md
  content/docs/guides/continuous-delivery/spinnaker.md
Labels: automation/merge

#5508 Update Azure create-project.md
  content/docs/get-started/azure/create-project.md
Labels: area/docs

#5592 Add Hitesh to the team page
  data/team/team/hitesh-boinpally.toml
  static/images/team/hitesh-boinpally.jpg
Labels: area/www

#5595 adjust pulumiup button styles
  assets/sass/_pulumi-up.scss
  layouts/page/pulumi-up.html
Labels: area/www

#5564 update docs for team admin permissions++
  content/docs/intro/console/accounts-and-organizations/accounts.md
  content/docs/intro/console/accounts-and-organizations/organizations.md
  content/docs/intro/console/collaboration/_index.md
  content/docs/intro/console/collaboration/auditing.md
  content/docs/intro/console/collaboration/organization-roles.md
  content/docs/intro/console/collaboration/project-and-stack-management.md
  content/docs/intro/console/collaboration/stack-permissions.md
  content/docs/intro/console/collaboration/teams.md
  content/docs/intro/console/extensions/ci-cd-integration-assistant.md
  content/docs/intro/console/extensions/pulumi-button.md
  static/images/docs/reference/service/org-settings-card.png
  static/images/docs/reference/service/organization-stacks.png
  static/images/docs/reference/service/resource-changes.png
  static/images/docs/reference/service/stack-resource-list.png
  static/images/docs/reference/service/timeline.png
Labels: area/docs
