Repository pulumi/docs, pull requests merged in 2024-08, with the labels that each got.

#12424 Adding Aptos Labs Case Study
  content/case-studies/aptos.md
  static/logos/customers/aptos.png
Labels: area/www

#12296 feat: add new blog Pulumi in a Cloud Native World
  content/blog/pulumi-in-a-cloud-native-world/a.png
  content/blog/pulumi-in-a-cloud-native-world/b.png
  content/blog/pulumi-in-a-cloud-native-world/base.png
  content/blog/pulumi-in-a-cloud-native-world/e.png
  content/blog/pulumi-in-a-cloud-native-world/ignite.png
  content/blog/pulumi-in-a-cloud-native-world/index.md
  content/blog/pulumi-in-a-cloud-native-world/k.png
  content/blog/pulumi-in-a-cloud-native-world/k2.png
  content/blog/pulumi-in-a-cloud-native-world/meta.png
  content/blog/pulumi-in-a-cloud-native-world/order.png
  content/blog/pulumi-in-a-cloud-native-world/order_cluster.png
  content/blog/pulumi-in-a-cloud-native-world/order_rest.png
  content/blog/pulumi-in-a-cloud-native-world/p.png
Labels: area/blog

#12414 [Platform Engineering] Blog #1 "Pulumi Patterns and Practices (P3): A Pulumi-based reference architecture for large-scale organizations"
  content/blog/pulumi-patterns-and-practices/index.md
  content/blog/pulumi-patterns-and-practices/meta.png
  content/blog/pulumi-patterns-and-practices/pulumi-ide.png
Labels: area/blog

#12473 Add author data for Gavin Johnson
  data/team/team/gavin-johnson.toml
  static/images/team/gavin-johnson.jpg
Labels: impact/no-changelog-required

#12578 updating about pulumi page
  content/about/_index.md
  static/images/team/james-denyer.jpg
Labels: impact/no-changelog-required
