Repository pulumi/docs, pull requests merged in 2025-05, with the labels that each got.

#15038 Use repo-specific ESC environment
  .github/workflows/add-to-project.yml
  .github/workflows/automerge-workflow.yml
  .github/workflows/bucket-cleanup-testing.yml
  .github/workflows/bucket-cleanup.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/check-lighthouse.yml
  .github/workflows/check-links.yml
  .github/workflows/check-search-urls.yml
  .github/workflows/customer-managed-deployment-agent-cli.yml
  .github/workflows/esc-cli.yml
  .github/workflows/export-repo-secrets.yml
  .github/workflows/generate-provider-docs.yml
  .github/workflows/pr-closed.yml
  .github/workflows/pull-request.yml
  .github/workflows/pulumi-cli-dev-version.yml
  .github/workflows/pulumi-cli.yml
  .github/workflows/scheduled-test.yml
  .github/workflows/scheduled-upgrade-programs.yml
  .github/workflows/scheduled-upstream-sync.yaml
  .github/workflows/testing-build-and-deploy.yml
  .github/workflows/update-search-index.yml
Labels: impact/no-changelog-required

#14899 Excluding targets from stack operations
  content/blog/excluding-targets-from-stack-operations/index.md
  content/blog/excluding-targets-from-stack-operations/meta.png
  data/team/team/tom-harding.toml
  static/images/team/tom-harding.jpg
Labels: area/blog

#15031 Rename Visual IaC Import to Visual Import
  content/blog/visual-import/index.md
  content/blog/visual-import/meta.png
  content/blog/visual-import/visual-iac-import.png
  content/docs/iac/adopting-pulumi/visual-import/_index.md
  content/docs/pulumi-cloud/import/_index.md
Labels: kind/task

#14455 feat: update company, role, and image for Anthony King
  data/team/team/anthony-king.toml
  static/images/team/anthony-king.jpg
Labels: awaiting-feedback

#15057 [ESC] Add text about tagging environments in the UI
  assets/js/bundle.js
  content/docs/esc/environments/envtagui.png
  content/docs/esc/environments/working-with-environments.md
Labels: area/docs, product/esc
